PLG-34: excluding orders without email
Metrilo/WooCommerce-Plugin pull request #29
Opened 2018-10-16 14:24 UTC by nedick007

2018-10-19 12:02 UTC, adamof requested changes
There is something very wrong with the indentation. Can you fix the indentation in one commit and do you changes in the next one?

2018-10-23 09:33 UTC, nedick007 commented
Problem with indentation was caused by if statement wrapping huge amount of code. Reworked the condition and code is ready for review.

2018-10-25 12:19 UTC, adamof commented
You didn't get me. I was asking you to fix do two commits:

1. Commit fixing the indentation in the whole file (tabs -> spaces)
2. Commit fixing the problem (orders without email)

2018-10-25 14:56 UTC, nedick007 commented
@adamof ready for review

2018-10-26 11:30 UTC, adamof commented on includes/integration.php
> -	private $integration_version = '1.7.9';
Why did you remove this?

2018-10-29 13:30 UTC, nedick007 commented
@adamof ready for review

2018-10-29 13:59 UTC, nedick007 commented
@adamof bump review

2018-10-30 06:35 UTC, adamof approved these changes

2018-10-30 11:12 UTC, merged